[package]
name = "metrixfolio-api"
version = "0.1.1"
edition = "2024"

[dependencies]
axum = "0.8.6"
tokio = { version = "1.0", features = ["full"]}
dotenv = "0.15"
reqwest = {version = "0.12.24", features = ["json"]}
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
hmac = "0.12.1"
sha2 = "0.10.9"
base64 = "0.22.1"
chrono = "0.4.42"
csv = "1.4.0"
tower-http = {version = "0.6.6", features = ["cors"]}
axum-firebase-middleware = "0.1.0"
firestore = {version = "0.47.0"}
tokio-stream = "0.1.17"
tempfile = "3.23.0"
gcp_auth = {version = "0.12.4"}
