[package]
name = "metrixfolio-api"
version = "0.1.1"
edition = "2024"

[dependencies]
axum = { version = "0.8.7", features = [ "macros"]}
tokio = { version = "1.0", features = ["full"]}
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
reqwest = {version = "0.12.24", features = ["json"]}
dotenv = "0.15"
tower-http = {version = "0.6.6", features = ["cors"]}
chrono = "0.4.42"
csv = "1.4.0"
tokio-stream = "0.1.17"
tempfile = "3.23.0"
gcp_auth = {version = "0.12.4"}
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

# Cryptography and hashing
hmac = "0.12.1"
sha2 = "0.10.9"
base64 = "0.22.1"

# XML Parser
quick-xml = {version = "0.38.4", features = ["serialize"] }

# Firestore
firestore = {version = "0.47.0"}
firebase-auth = "0.5.1"
futures = "0.3.31"

