name: Deploy Frontend (metrixfolio-fe) on Tag

on:
  push:
    tags:
      - 'v*'

env:
  GCP_PROJECT_ID: '${{ secrets.GCP_PROJECT_ID }}'
  GCP_SA_KEY: '${{ secrets.FIREBASE_SA_KEY }}'
  GCP_REGION: 'europe-west3'
  API_SERVICE_NAME: 'metrixfolio-api'
  API_IMAGE_REPO: 'metrixfolio-registry'

jobs:
  deploy-frontend:
    name: Deploy metrixfolio-fe to Firebase App Hosting
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy metrixfolio-fe to App Hosting
        run: |
          cd metrixfolio-fe
          firebase deploy --project=${{ secrets.GCP_PROJECT_ID }} --only apphosting:metrixfolio --token ${{ secrets.FIREBASE_TOKEN }}

  deploy-backend:
    name: Deploy metrixfolio-api (Backend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCP_SA_KEY }}'

      - name: Setup Google Cloud CLI
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Get Tag Name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        
      - name: Build and Push Docker Image
        run: |
          export IMAGE_TAG="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.API_IMAGE_REPO }}/${{ env.API_SERVICE_NAME }}:${{ steps.get_tag.outputs.TAG_NAME }}"
          
          echo "Building image: $IMAGE_TAG"
          
          cd metrixfolio-api
          docker build -t $IMAGE_TAG .
          
          echo "Pushing image: $IMAGE_TAG"
          docker push $IMAGE_TAG

      - name: Deploy to Cloud Run
        run: |
          export IMAGE_TAG="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.API_IMAGE_REPO }}/${{ env.API_SERVICE_NAME }}:${{ steps.get_tag.outputs.TAG_NAME }}"
          
          echo "Deploying image to Cloud Run service: ${{ env.API_SERVICE_NAME }}"
          
          gcloud run deploy ${{ env.API_SERVICE_NAME }} \
            --image $IMAGE_TAG \
            --region ${{ env.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-secrets=KRAKEN_API_KEY=METRIXFOLIO_KRAKEN_KEY:latest,KRAKEN_API_SECRET=METRIXFOLIO_KRAKEN_SECRET:latest,GOOGLE_SHEET_CSV_URL=METRIXFOLIO_GOOGLE_SHEET_URL:latest,IBKR_TOKEN=METRIXFOLIO_IBKR_TOKEN:latest,IBKR_QUERY_ID=METRIXFOLIO_IBKR_QUERY_ID:latest,TWELVE_DATA_API_KEY=METRIXFOLIO_TWELVE_DATA_API_KEY:latest \
            --set-env-vars=FIREBASE_PROJECT_ID=${{ env.GCP_PROJECT_ID }}

  deploy-broadcaster:
    name: Deploy Broadcaster
    runs-on: ubuntu-latest
    #needs: [deploy-frontend, deploy-backend]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCP_SA_KEY }}'

      - name: Setup Google Cloud CLI
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Get Tag Name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        
      - name: Build and Push Broadcaster Image
        run: |
          # Docker Repo and Image Name
          export BROADCASTER_IMAGE="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.API_IMAGE_REPO }}/broadcaster:${{ steps.get_tag.outputs.TAG_NAME }}"
          
          echo "Building image: $BROADCASTER_IMAGE"
          
          cd broadcaster
          docker build -t $BROADCASTER_IMAGE .
          
          echo "Pushing image: $BROADCASTER_IMAGE"
          docker push $BROADCASTER_IMAGE

      - name: Deploy Broadcaster to Cloud Run
        run: |
          export BROADCASTER_IMAGE="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.API_IMAGE_REPO }}/broadcaster:${{ steps.get_tag.outputs.TAG_NAME }}"
          
          gcloud run deploy broadcaster \
            --image $BROADCASTER_IMAGE \
            --region ${{ env.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-secrets=TELEGRAM_BOT_TOKEN=METRIXFOLIO_TELEGRAM_TOKEN:latest,TELEGRAM_CHANNEL_ID=METRIXFOLIO_TELEGRAM_CHANNEL_ID:latest,NOTIFIER_API_SECRET=METRIXFOLIO_NOTIFIER_SECRET:latest

      - name: Notify Telegram (Deployment Success)
        run: |
          # Broadcaster URL'ini dinamik alalım
          SERVICE_URL=$(gcloud run services describe broadcaster --region ${{ env.GCP_REGION }} --format 'value(status.url)')
          
          curl -X POST $SERVICE_URL/tlg-send-message \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.NOTIFIER_API_SECRET }}" \
          -d '{"text": "✅ *Deployment Completed!*\n\nFrontend, Backend, and Broadcaster have been updated. 🚀"}'