name: Deploy Frontend (metrixfolio-fe) on Tag

on:
  push:
    tags:
      - 'v*'
  
  workflow_dispatch:
    inputs:
      deploy_frontend:
        description: 'Frontend Deploy?'
        type: boolean
        default: true
      deploy_backend:
        description: 'Backend Deploy?'
        type: boolean
        default: true
      deploy_broadcaster:
        description: 'Broadcaster Deploy?'
        type: boolean
        default: true

env:
  GCP_PROJECT_ID: '${{ secrets.GCP_PROJECT_ID }}'
  GCP_SA_KEY: '${{ secrets.FIREBASE_SA_KEY }}'
  GCP_REGION: 'europe-west3'
  API_SERVICE_NAME: 'metrixfolio-api'
  API_IMAGE_REPO: 'metrixfolio-registry'

jobs:
  deploy-frontend:
    name: Deploy metrixfolio-fe to Firebase App Hosting
    runs-on: ubuntu-latest

    if: |
      (github.event_name == 'workflow_dispatch' && inputs.deploy_frontend == true) ||
      (github.event_name == 'push' && (contains(github.ref, '-fe') || (!contains(github.ref, '-be') && !contains(github.ref, '-bot'))))

    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy metrixfolio-fe to App Hosting
        run: |
          cd metrixfolio-fe
          firebase deploy --project=${{ secrets.GCP_PROJECT_ID }} --only apphosting:metrixfolio --token ${{ secrets.FIREBASE_TOKEN }}